data:
  AzureWebJobsStorage: VXNlRGV2ZWxvcG1lbnRTdG9yYWdlPXRydWU=
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0
apiVersion: v1
kind: Secret
metadata:
  name: samplehttpapplication1
  namespace: default
---
data:
  host.master: RDBuUXBZcWVONEZKQlhXdk1nRDJZbDBiV1gyMGFXL1BxT0drOUpJNXpqL2x5YzZLYUJhdGJ3PT0=
  host.function.default: UnVoOXZ0eUx3d3UzQkE1aExNZ0E0dkJhbW1vQzkvNVgwYkFoQ1V5VWpvUDJMV2NIN240WjNnPT0=
  host.systemKey.default: dzY1ZTVpM0QwNlU2WExsdkZFVzBGV0JDM0VEN3h1VjVGNzllT2RKWHFreTJ1TTFqeG5CS213PT0=
  functions.samplehttpapplication1.default: U3NnTW55bXBwdEF2elhlSWx3TFdiRlowRzZxUDZWd0dSa0luQzFRZlBuRGxwRHlTZ2pLMnhRPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-samplehttpapplication1
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: samplehttpapplication1-function-keys-identity-svc-act
  namespace: default
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
  namespace: default
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: samplehttpapplication1-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: samplehttpapplication1-function-keys-identity-svc-act-functions-keys-manager-rolebinding
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: samplehttpapplication1-http
  namespace: default
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: samplehttpapplication1-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplehttpapplication1-http
  namespace: default
  labels:
    app: samplehttpapplication1-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplehttpapplication1-http
  template:
    metadata:
      labels:
        app: samplehttpapplication1-http
    spec:
      containers:
      - name: samplehttpapplication1-http
        image: demofunctionsonaks01.azurecr.io/functionapphttptrigger1:latest
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: SampleHttpApplication1
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-samplehttpapplication1
        envFrom:
        - secretRef:
            name: samplehttpapplication1
      serviceAccountName: samplehttpapplication1-function-keys-identity-svc-act
---